### PR TITLE
Changed timeout_millis to delay, allowing reload to wait until the server is up

### PR DESCRIPTION
**Pull request by alallier**
This feature changes the timeout_millis to delay. Now you can enter true in for a delay and reload will wait and check for the server to be up before it reloads.

### CODE REVIEW

**Comment by jprichardson** [comment]
I really like the idea behind this. Why add use `XMLHttpRequest` to check server status? Why not use Websockets themselves? We could probably dump Sockjs, but I suppose that should be handled in a different issue.

Thanks for your help.

**Comment by alallier** [comment]
As far as i can tell the socket is closed when the server goes down, so we need to keep pinging the server to see if it’s up. Using a XHR seemed like the simplest way to do that, but i’m open to suggestions for other approaches.

**Comment by jprichardson** [comment]
> Using a XHR seemed like the simplest way to do that, but i’m open to suggestions for other approaches.

What I meant was, why not just attempt to reopen a connection a new websocket to determine the status of the server?

**Comment by alallier** [comment]
With my latest commit, I rewrote reload-client.js to use sockets instead of xhr requests

**Pull request merged**
