### PR TITLE
separate configuration of app routing from starting web socket server

### PR DESCRIPTION
**Pull request by peterwillis**

### CODE REVIEW

**Comment by peterwillis** [comment]
I am not sure what to do about the broken build. It is not in the code I added. It is because some dependencies have dropped support for node 0.12 and 0.1.

**Comment by peterwillis** [comment]
It looks like it is from the 'standard' module, which now only supports version 4 as a minimum. You have the choice here:

Force the use of an earlier version of standard or drop support for node 0.12 and 0.1. Please let me know which and I will make the changes.

**Comment by alallier** [comment]
I failed to notice this was also failing on master, thanks for pointing this out. I'll fix it in a separate PR and you can pull the changes into your branch

**Comment by alallier** [comment]
I upgraded Standard now, should be able to pull Upstream into your branch.

**Comment by peterwillis** [comment]
It looks like Standard has a minimum version of node v4 now. You can see it in the package.json under the engine section:

https://github.com/feross/standard/blob/master/package.json

Maybe for v2.0.0 it would be ok to drop support for node 0.1 and 0.12? Either that or drop the version of Standard

**Comment by jprichardson** [comment]
> Maybe for v2.0.0 it would be ok to drop support for node 0.1 and 0.12? Either that or drop the version of Standard

Yep, we don't need Node v0.10, or v0.12 - they don't even receive maintenance support anymore.

**Comment by alallier** [comment]
I agree @jprichardson but the build is passing now with the Standard bump

**Comment by yamboy1** [comment]
I agree with @jprichardson. See #73

**Comment by yamboy1** [comment]
Brilliant idea @peterwillis. I can't believe I didn't think of putting in versions 6 and 7, even though I am running version 6 at the moment

**Comment by peterwillis** [comment]
I meant to do it in a separate pr!

**Comment by yamboy1** [comment]
Just create a new branch, make the change and make the seperate pr.

**Comment by alallier** [comment]
Looks good to me, thanks for keeping it brackwards compatiable! Thanks @peterwillis, going to merge into the version 2.0.0 branch, should be in master soon once everything for version 2 is done 😄

**Pull request merged**
